#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Nov 04, 2020 02:58:15 PM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    image20 "../../../../../../../page/LeeOpticianslogo.jpg" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 756x453+324+81
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Customer Form"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    entry $top.ent45 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$top.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$top.ent46" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$top.ent47" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$top.ent48" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$top.ent49" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text CustomerID* 
    vTcl:DefineAlias "$top.lab51" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text BranchID* 
    vTcl:DefineAlias "$top.lab52" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Name* 
    vTcl:DefineAlias "$top.lab53" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Surname* 
    vTcl:DefineAlias "$top.lab54" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Date of Birth*} 
    vTcl:DefineAlias "$top.lab55" "Label5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$top.ent56" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$top.ent53" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$top.ent54" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$top.ent55" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$top.ent57" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab59 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Town* 
    vTcl:DefineAlias "$top.lab59" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Postcode* 
    vTcl:DefineAlias "$top.lab60" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab62 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Email Address*} 
    vTcl:DefineAlias "$top.lab62" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Telephone* 
    vTcl:DefineAlias "$top.lab64" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Medical Conditions} 
    vTcl:DefineAlias "$top.lab65" "Label11" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -text {Fields marked with * are mandatory} 
    vTcl:DefineAlias "$top.lab66" "Label12" vTcl:WidgetProc "Toplevel1" 1
    button $top.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Add Record} 
    vTcl:DefineAlias "$top.but67" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Close Form} 
    vTcl:DefineAlias "$top.but68" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab72 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -image image20 \
        -text Label 
    vTcl:DefineAlias "$top.lab72" "Label9" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent45 \
        -in $top -x 0 -relx 0.244 -y 0 -rely 0.407 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.244 -y 0 -rely 0.325 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.244 -y 0 -rely 0.489 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.244 -y 0 -rely 0.569 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.244 -y 0 -rely 0.65 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.061 -y 0 -rely 0.325 -width 0 -relwidth 0.188 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.102 -y 0 -rely 0.406 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.119 -y 0 -rely 0.486 -width 0 -relwidth 0.103 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.102 -y 0 -rely 0.57 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.081 -y 0 -rely 0.649 -width 0 -relwidth 0.144 \
        -height 0 -relheight 0.057 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.244 -y 0 -rely 0.73 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.663 -y 0 -rely 0.332 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.663 -y 0 -rely 0.42 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.663 -y 0 -rely 0.509 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.661 -y 0 -rely 0.596 -width 194 -relwidth 0 \
        -height 80 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.135 -y 0 -rely 0.731 -width 0 -relwidth 0.086 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.569 -y 0 -rely 0.331 -width 0 -relwidth 0.087 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.542 -y 0 -rely 0.419 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.556 -y 0 -rely 0.508 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.503 -y 0 -rely 0.596 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.053 -y 0 -rely 0.905 -width 0 -relwidth 0.254 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.82 -y 0 -rely 0.839 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 0 -relx 0.82 -y 0 -rely 0.905 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 0 -relx 0.357 -y 0 -rely 0.066 -width 0 -relwidth 0.284 \
        -height 0 -relheight 0.179 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

