#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Nov 12, 2020 11:35:33 AM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    leeopticianslogo_jpg "../Users/ryanb/OneDrive - C2k/A2 2020-2021/Computer Science/A2 Unit 5/Code/LeeOpticianslogo.jpg" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background #ffffff 
    wm focusmodel $top passive
    wm geometry $top 600x716+416+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Customer Form"
    vTcl:DefineAlias "$top" "CustomerForm" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent46" "CustomerEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent47 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent47" "BranchEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent48" "NameEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent49" "SurnameEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent50" "DOBEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent51" "TownEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent52" "PostcodeEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent53" "EmailEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent54" "TelephoneEntry" vTcl:WidgetProc "CustomerForm" 1
    entry $top.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$top.ent55" "MedicalEntry" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab56 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text CustomerID 
    vTcl:DefineAlias "$top.lab56" "CustomerLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab57 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text BranchID 
    vTcl:DefineAlias "$top.lab57" "BranchLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab58 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Name 
    vTcl:DefineAlias "$top.lab58" "NameLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab59 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Surname 
    vTcl:DefineAlias "$top.lab59" "SurnameLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab60 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -image leeopticianslogo_jpg -text Label 
    vTcl:DefineAlias "$top.lab60" "Label5" vTcl:WidgetProc "CustomerForm" 1
    frame $top.fra61 \
        -borderwidth 2 -relief groove -background #ffffff -height 474 \
        -width 145 
    vTcl:DefineAlias "$top.fra61" "Frame1" vTcl:WidgetProc "CustomerForm" 1
    set site_3_0 $top.fra61
    button $site_3_0.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Add 
    vTcl:DefineAlias "$site_3_0.but68" "AddCustomerBtn" vTcl:WidgetProc "CustomerForm" 1
    button $site_3_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$site_3_0.but69" "SearchCustomerBtn" vTcl:WidgetProc "CustomerForm" 1
    button $site_3_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Delete 
    vTcl:DefineAlias "$site_3_0.but70" "DeleteCustomerBtn" vTcl:WidgetProc "CustomerForm" 1
    button $site_3_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Update 
    vTcl:DefineAlias "$site_3_0.but71" "UpdateCustomerBtn" vTcl:WidgetProc "CustomerForm" 1
    button $site_3_0.but72 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Close Form} 
    vTcl:DefineAlias "$site_3_0.but72" "CustomerCloseBtn" vTcl:WidgetProc "CustomerForm" 1
    place $site_3_0.but68 \
        -in $site_3_0 -x 0 -relx 0.276 -y 0 -rely 0.042 -width 63 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 0 -relx 0.276 -y 0 -rely 0.148 -width 66 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 0 -relx 0.276 -y 0 -rely 0.253 -width 64 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 0 -relx 0.276 -y 0 -rely 0.359 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but72 \
        -in $site_3_0 -x 0 -relx 0.207 -y 0 -rely 0.907 -width 91 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab62 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Date of Birth} 
    vTcl:DefineAlias "$top.lab62" "DOBLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab63 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Town 
    vTcl:DefineAlias "$top.lab63" "TownLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab64 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Postcode 
    vTcl:DefineAlias "$top.lab64" "PostcodeLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab65 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Email 
    vTcl:DefineAlias "$top.lab65" "EmailLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab66 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Telephone 
    vTcl:DefineAlias "$top.lab66" "TelephoneLbl" vTcl:WidgetProc "CustomerForm" 1
    label $top.lab67 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Medical Conditions} 
    vTcl:DefineAlias "$top.lab67" "MedicalLbl" vTcl:WidgetProc "CustomerForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent46 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.251 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.307 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.363 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.419 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.475 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.531 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.587 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.642 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.698 -width 234 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.754 -width 234 -relwidth 0 \
        -height 70 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.251 -width 0 -relwidth 0.115 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.307 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.028 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.363 -width 0 -relwidth 0.063 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.419 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.098 -width 0 -relwidth 0.29 \
        -height 0 -relheight 0.085 -anchor nw -bordermode ignore 
    place $top.fra61 \
        -in $top -x 0 -relx 0.667 -y 0 -rely 0.223 -width 0 -relwidth 0.242 \
        -height 0 -relheight 0.662 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.475 -width 0 -relwidth 0.12 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.531 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.587 -width 0 -relwidth 0.108 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.117 -y 0 -rely 0.642 -width 0 -relwidth 0.073 \
        -height 0 -relheight 0.028 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.698 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.028 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -y 0 -rely 0.754 -width 0 -relwidth 0.182 -height 0 \
        -relheight 0.029 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

