#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Mar 14, 2021 03:15:37 PM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    leeopticianslogo_jpg "../Users/ryanb/OneDrive - C2k/A2 2020-2021/Computer Science/A2 Unit 5/Code/LeeOpticianslogo.jpg" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top71 {base} {
    global vTcl
    if {$base == ""} {
        set base .top71
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #ffffff 
    wm focusmodel $top passive
    wm geometry $top 600x696+381+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Prescription Form"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab72 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -image leeopticianslogo_jpg -text Label 
    vTcl:DefineAlias "$top.lab72" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra73 \
        -borderwidth 2 -relief groove -background #ffffff -height 345 \
        -width 125 
    vTcl:DefineAlias "$top.fra73" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra73
    button $site_3_0.but84 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Add 
    vTcl:DefineAlias "$site_3_0.but84" "AddButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but85 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$site_3_0.but85" "SearchButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Update 
    vTcl:DefineAlias "$site_3_0.but88" "UpdateButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but89 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Print Prescription} 
    vTcl:DefineAlias "$site_3_0.but89" "PrintButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but90 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Close Form} 
    vTcl:DefineAlias "$site_3_0.but90" "CloseButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but84 \
        -in $site_3_0 -x 0 -relx 0.24 -y 0 -rely 0.058 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but85 \
        -in $site_3_0 -x 0 -relx 0.24 -y 0 -rely 0.203 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 0 -relx 0.24 -y 0 -rely 0.493 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but89 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.638 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but90 \
        -in $site_3_0 -x 0 -relx 0.16 -y 0 -rely 0.87 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab74 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text PrescriptionID 
    vTcl:DefineAlias "$top.lab74" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent75 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 284 
    vTcl:DefineAlias "$top.ent75" "PresIDEntry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent76 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 284 
    vTcl:DefineAlias "$top.ent76" "PresDateEntry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent77 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 284 
    vTcl:DefineAlias "$top.ent77" "CustomerIDEntry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent78 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 284 
    vTcl:DefineAlias "$top.ent78" "PresDetailsEntry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent79 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 284 
    vTcl:DefineAlias "$top.ent79" "StaffIDEntry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab80 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text PrescriptionDate 
    vTcl:DefineAlias "$top.lab80" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab81 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text CustomerID 
    vTcl:DefineAlias "$top.lab81" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab82 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text PrescriptionDetails 
    vTcl:DefineAlias "$top.lab82" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab83 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text StaffID 
    vTcl:DefineAlias "$top.lab83" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but87 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Delete 
    vTcl:DefineAlias "$top.but87" "DeleteButton" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab72 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.144 -width 0 -relwidth 0.29 \
        -height 0 -relheight 0.059 -anchor nw -bordermode ignore 
    place $top.fra73 \
        -in $top -x 0 -relx 0.733 -y 0 -rely 0.273 -width 0 -relwidth 0.208 \
        -height 0 -relheight 0.496 -anchor nw -bordermode ignore 
    place $top.lab74 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.302 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.ent75 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.302 -width 284 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent76 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.359 -width 284 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent77 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.417 -width 284 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent78 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.474 -width 284 -relwidth 0 \
        -height 90 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent79 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.632 -width 284 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab80 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.359 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.lab81 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.417 -width 0 -relwidth 0.132 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.lab82 \
        -in $top -x 0 -y 0 -rely 0.474 -width 0 -relwidth 0.173 -height 0 \
        -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.lab83 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.632 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.but87 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.445 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top71 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

